### ISSUE TITLE
near future solar patches broken

### ISSUE THREAD

**Issue by redPanther** [net-lisias-ksp/TweakScaleCompanion_NFS#1]
Hi,
I realized that nfs changed the part names in latest version. can you adopt the changes? 
see here for the new names: https://github.com/ChrisAdderley/NearFutureSolar/blob/master/GameData/NearFutureSolar/Localization/en-us.cfg

thx!

**Comment by Lisias** [comment]
Congrats, @redPanther ! You opened the first issue for the first TweakScale Companion Pack! :)

**Comment by Lisias** [comment]
These are the new parts:

* nfs-panel-static-curved-375-1
* nfs-panel-static-curved-25-1
* nfs-panel-deploying-advanced-1x3-orion-2
* nfs-panel-deploying-advanced-1x5-goes-1
* nfs-panel-deploying-advanced-3x1-hayabusa-1
* nfs-panel-deploying-advanced-1x1-ikonos-1
* nfs-panel-deploying-advanced-1x3-orion-1
* nfs-panel-deploying-advanced-1x2-mro-1
* nfs-panel-deploying-advanced-2x6x6-lab-1
* nfs-panel-deploying-advanced-1x1-messenger-1
* nfs-panel-deploying-advanced-1x5-dawn-1
* nfs-panel-deploying-advanced-1x4-dragon-2
* nfs-panel-deploying-advanced-2x20-hub-1
* nfs-panel-deploying-advanced-1x4-dragon-1
* nfs-panel-deploying-advanced-3x1-wv3-1
* nfs-panel-deploying-advanced-3x1-tdrss-1
* nfs-panel-deploying-advanced-1x2-wv4-1
* nfs-panel-deploying-curved-375-1
* nfs-panel-deploying-curved-25-1
* nfs-panel-deploying-concentrator-1x4-juno-1
* nfs-panel-deploying-concentrator-1x3x1-juice-1
* nfs-panel-static-truss-1
* nfs-panel-static-truss-3
* nfs-panel-static-truss-2
* nfs-panel-deploying-blanket-bfs-1
* nfs-panel-deploying-blanket-arm-1
* nfs-panel-deploying-blanket-starship-1
* nfs-panel-deploying-blanket-dst-1
* nfs-panel-deploying-blanket-copernicus-1
* nfs-panel-deploying-blanket-dsg-1
* nfs-panel-deploying-blanket-orion-1
* nfs-panel-deploying-blanket-drm-1
* nfs-panel-deploying-blanket-nautilus-1

**Comment by Lisias** [comment]
Known Issue. The following parts will not be scalable until support for ModulePartVariant is implemented in TweakScale:

* nfs-panel-deploying-curved-25-1
* nfs-panel-static-truss-1
* nfs-panel-static-truss-2
* nfs-panel-static-truss-3.
* nfs-panel-deploying-blanket-starship-1

**Comment by Lisias** [comment]
@redPanther , on the following link:

https://github.com/net-lisias-ksp/TweakScaleCompanion_NFS/releases

You will find the initial BETA release for the TweakScale support for NFS 1.1 .

It's expected that you can safely install the Companion together the current release for TweakScale, as there're cleaning procedures to remove deprecated patches in order to avoid conflicts.

Please download it on a **DISPOSABLE** instalment for testing!

Cheers!

**Comment by redPanther** [comment]
I will test it and give you Feedback. Thx
